spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/5danjam
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none

  level:
    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.web.servlet: DEBUG
#    org.springframework.web.filter: DEBUG

